application: hangouts-against-humanity
version: 1
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static
  http_headers:
    Access-Control-Allow-Origin: '*'
- url: /.*
  script: _go_app